#!/usr/bin/env bash
#
# make-sfx.sh — regenerate the UI sound palette for the release video.
#
# The palette comes from TWO sources, and the split matters:
#
#   A. SYNTHESISED IN-SCRIPT (tap, confirm, rest-start, rest-done, impact,
#      count, pop). Built from scratch by ffmpeg — sine / aevalsrc /
#      anoisesrc. These are genuinely regenerated on every run, and are
#      byte-identical every time: noise sources are seeded and level setting
#      is a measure-then-apply-exact-gain pass, not a dynamics processor.
#      Editing the recipe here changes the sound.
#
#   B. GENERATED BY THE ElevenLabs SOUND MODEL, then finished here (ding,
#      swoosh, tick, screen, fill, reveal, sweep). The API is NOT
#      deterministic — the same prompt returns different audio on every call —
#      so the reproducible source is the checked-in MP3 under
#      public/sfx/src/, not the prompt. This script only trims, EQs, fades and
#      normalises those files; it never calls the network. Editing the recipe
#      here changes the trim/EQ/level, NOT the underlying performance; to
#      change that you must generate a new MP3 and commit it.
#      public/sfx/src/PROMPTS.md records every prompt, plus the prompts that
#      failed and the measured reason why.
#
# Either way the script is the single source of truth for what ships: no file
# in public/sfx/ is hand-edited, and a clean run reproduces all 14.
#
# Output: remotion-release/public/sfx/*.wav — 48 kHz, stereo, 16-bit PCM.
#
# LEVELS. Every sound is peak-normalised to the SAME target, -3 dBFS, via
# `finish <name> -3`. Keep it that way when adding sounds.
#
# The perceived hierarchy — which cue is loud, which sits back — lives entirely
# in src/Sound.tsx's LEVEL map. It used to be encoded here as well (tap -14,
# confirm -10, count -20, ...) and every cue was consequently attenuated twice.
# One source of truth: this script makes each file as loud as it can cleanly be,
# and the timeline decides how loud it should actually sound.
#
# Note that equal peak still does not mean equal loudness: the transients
# (tap/tick/count/pop) carry a ~22-24 dB peak-to-momentary-loudness crest while
# the sustained tonal cues carry only ~6-9 dB. That is a property of the sounds,
# not of the normalisation, and the LEVEL map is the right place to correct it.
#
# Usage (from anywhere, including the repo root):
#   ./remotion-release/tools/make-sfx.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="$SCRIPT_DIR/../public/sfx"
mkdir -p "$OUT_DIR"
OUT_DIR="$(cd -- "$OUT_DIR" && pwd)"
SRC_DIR="$OUT_DIR/src"          # checked-in ElevenLabs MP3s (see PROMPTS.md there)

command -v ffmpeg  >/dev/null || { echo "make-sfx: ffmpeg not found on PATH" >&2; exit 1; }
command -v ffprobe >/dev/null || { echo "make-sfx: ffprobe not found on PATH" >&2; exit 1; }

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

SR=48000

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

# Build an intermediate 32-bit float working file from a filter_complex graph.
# Working in float means the envelope/mix maths never quantises twice; the
# single 16-bit conversion happens in finish().
#
# Each sound is synthesised mono and widened with an explicit unity-gain pan.
# That is deliberate: ffmpeg's automatic mono->stereo rematrix applies a -3 dB
# pan law, which would silently undershoot every level target set below.
#   synth <name> <filter_complex ending in [out]>
synth() {
  local name="$1" graph="$2"
  ffmpeg -y -hide_banner -loglevel error \
    -filter_complex "$graph;[out]pan=stereo|c0=c0|c1=c0[st]" -map '[st]' \
    -c:a pcm_f32le -ar "$SR" "$TMP_DIR/$name.wav"
}

# Highest "Peak level dB" astats reports across channels (i.e. true sample peak).
peak_dbfs() {
  ffmpeg -hide_banner -nostats -i "$1" -af astats=metadata=1 -f null - 2>&1 \
    | sed -n 's/.*Peak level dB: //p' | sort -g | tail -n1
}

# Measure the working file's peak, apply the exact linear gain that lands it on
# the requested target, and write the deliverable as 48 kHz / stereo / s16.
# Deterministic and idempotent — no limiter, no loudnorm two-pass drift.
#   finish <name> <target_peak_dbfs>
finish() {
  local name="$1" target="$2" src="$TMP_DIR/$1.wav" peak gain
  peak="$(peak_dbfs "$src")"
  gain="$(awk -v p="$peak" -v t="$target" 'BEGIN { printf "%.6f", t - p }')"
  ffmpeg -y -hide_banner -loglevel error -i "$src" \
    -af "volume=${gain}dB" \
    -ar "$SR" -ac 2 -c:a pcm_s16le "$OUT_DIR/$name.wav"
  printf '  %-14s %6.1f dBFS peak\n' "$name.wav" "$(peak_dbfs "$OUT_DIR/$name.wav")"
}

# Finish an ElevenLabs-generated MP3 into a delivered WAV.
#
# The model returns 44.1 kHz stereo MP3, usually with the wanted event buried
# somewhere inside a longer take (and often with extra events either side), so
# every one of these needs an explicit trim window found by measuring the file
# rather than by ear. asetpts after atrim rebases timestamps to zero so the
# afade start times below are relative to the trimmed clip, not the source.
#   fromsrc <name> <src.mp3> <trim_start_s> <dur_s> <fade_in_s> <fade_out_s> [extra filters]
fromsrc() {
  local name="$1" src="$2" st="$3" du="$4" fi="$5" fo="$6" extra="${7:-anull}"
  local fostart
  fostart="$(awk -v d="$du" -v f="$fo" 'BEGIN { printf "%.4f", d - f }')"
  ffmpeg -y -hide_banner -loglevel error -i "$SRC_DIR/$src" \
    -af "atrim=start=${st}:duration=${du},asetpts=N/SR/TB,${extra},aresample=$SR,afade=type=in:start_time=0:duration=${fi}:curve=tri,afade=type=out:start_time=${fostart}:duration=${fo}:curve=tri" \
    -ar "$SR" -ac 2 -c:a pcm_f32le "$TMP_DIR/$name.wav"
  finish "$name" -3
}

echo "make-sfx: writing to $OUT_DIR"

# ---------------------------------------------------------------------------
# 1. tap.wav — soft UI tap, ~60 ms. Fingertip on glass.
#
#    [a] a white-noise burst pushed through two 2-pole lowpasses at 1.8 kHz
#        (24 dB/oct — the dull "contact" of skin, not the bright snap of a
#        mouse switch) with the low mud highpassed off at 250 Hz, then an
#        exponential fade-out so the burst is essentially over in 20 ms.
#        White rather than pink: pink's own -3 dB/oct tilt stacked on top of
#        the lowpass left nothing above 1.6 kHz, and the tap lost its contact
#        definition and read as a pure tone instead.
#    [b] a QUIET 560 Hz sine pip, 1.5 ms attack, 9 ms decay — the small pitched
#        "body" under the click. It must stay UNDER the noise, and that takes a
#        much lower gain than it looks like it should: a sustained sine carries
#        far more RMS than a burst of noise that has already decayed, so at 0.55
#        (and even at 0.30) the pip was still louder than the noise and the tap
#        read as a pitched boop. At 0.11 the noise leads the pip by ~4 dB, which
#        is what makes it a tap with a hint of pitch rather than a tone.
#    Mixed 1.0 : 0.11, 2 ms anti-click fade-in, 8 ms tail fade-out.
# ---------------------------------------------------------------------------
synth tap "
  anoisesrc=color=white:amplitude=0.9:duration=0.06:sample_rate=$SR:seed=101
    ,highpass=frequency=250:poles=2
    ,lowpass=frequency=1800:poles=2
    ,lowpass=frequency=1800:poles=2
    ,afade=type=out:start_time=0.002:duration=0.056:curve=exp
    ,volume=1.0[a];
  aevalsrc=exprs='sin(2*PI*560*t)*(1-exp(-t/0.0015))*exp(-t/0.009)':sample_rate=$SR:duration=0.06
    ,volume=0.11[b];
  [a][b]amix=inputs=2:normalize=0
    ,afade=type=in:start_time=0:duration=0.002:curve=tri
    ,afade=type=out:start_time=0.052:duration=0.008:curve=tri[out]"
finish tap -3

# ---------------------------------------------------------------------------
# 3. confirm.wav — two-note ascending confirm, ~180 ms. "Set logged."
#
#    A5 (880 Hz) then E6 (1318.5 Hz) — a rising perfect fifth, the most
#    unambiguously positive two-note interval there is.
#    Each note is a soft triangle: fundamental + 11% third harmonic + 4% fifth
#    harmonic. 5 ms attack (gentle, no click), 55 ms exponential decay.
#    Note two is offset 72 ms by adelay, so the pair lands at exactly 180 ms
#    with no reverb or ring-out beyond the natural decay.
# ---------------------------------------------------------------------------
synth confirm "
  aevalsrc=exprs='(sin(2*PI*880*t)+0.11*sin(2*PI*2640*t)+0.04*sin(2*PI*4400*t))*(1-exp(-t/0.005))*exp(-t/0.055)':sample_rate=$SR:duration=0.18
    ,volume=1.0[a];
  aevalsrc=exprs='(sin(2*PI*1318.5*t)+0.11*sin(2*PI*3955.5*t)+0.04*sin(2*PI*6592.5*t))*(1-exp(-t/0.005))*exp(-t/0.055)':sample_rate=$SR:duration=0.108
    ,volume=0.92
    ,adelay=delays=72:all=1[b];
  [a][b]amix=inputs=2:normalize=0
    ,afade=type=in:start_time=0:duration=0.003:curve=tri
    ,afade=type=out:start_time=0.172:duration=0.008:curve=tri[out]"
finish confirm -3

# ---------------------------------------------------------------------------
# 4. rest-start.wav — soft low double-pulse, ~220 ms. "Rest timer running."
#
#    Two muted A3 (220 Hz) pips, the second at 115 ms. Nearly pure sine — only
#    8% second harmonic — and a 700 Hz lowpass on top, so it sits underneath
#    everything else rather than announcing itself. 8 ms attack (deliberately
#    slower than the taps: this is a state change, not a hit), 45 ms decay.
#    Second pip at 0.85 gain so the pair reads as a soft falling pair.
# ---------------------------------------------------------------------------
synth rest-start "
  aevalsrc=exprs='(sin(2*PI*220*t)+0.08*sin(2*PI*440*t))*(1-exp(-t/0.008))*exp(-t/0.045)':sample_rate=$SR:duration=0.115
    ,volume=1.0[a];
  aevalsrc=exprs='(sin(2*PI*220*t)+0.08*sin(2*PI*440*t))*(1-exp(-t/0.008))*exp(-t/0.045)':sample_rate=$SR:duration=0.105
    ,volume=0.85
    ,adelay=delays=115:all=1[b];
  [a][b]amix=inputs=2:normalize=0
    ,lowpass=frequency=700:poles=2
    ,highpass=frequency=40:poles=2
    ,afade=type=in:start_time=0:duration=0.004:curve=tri
    ,afade=type=out:start_time=0.212:duration=0.008:curve=tri[out]"
finish rest-start -3

# ---------------------------------------------------------------------------
# 5. rest-done.wav — three ascending pips, ~320 ms. "Time's up."
#
#    G5 (784) → B5 (988) → D6 (1175): a G-major triad walked upwards, spaced
#    100 ms. Brighter than rest-start (10% third harmonic, no lowpass) and the
#    third pip is held longer (120 ms vs 100 ms, with a 55 ms decay instead of
#    40 ms) so the phrase resolves instead of stopping. The three pips also rise
#    in gain (0.80 / 0.90 / 1.00). Consonant triad + short attack = clearly
#    terminal without the dissonance or repetition that makes an alarm urgent.
# ---------------------------------------------------------------------------
synth rest-done "
  aevalsrc=exprs='(sin(2*PI*784*t)+0.10*sin(2*PI*2352*t))*(1-exp(-t/0.004))*exp(-t/0.040)':sample_rate=$SR:duration=0.10
    ,volume=0.80[a];
  aevalsrc=exprs='(sin(2*PI*988*t)+0.10*sin(2*PI*2964*t))*(1-exp(-t/0.004))*exp(-t/0.040)':sample_rate=$SR:duration=0.10
    ,volume=0.90
    ,adelay=delays=100:all=1[b];
  aevalsrc=exprs='(sin(2*PI*1175*t)+0.10*sin(2*PI*3525*t))*(1-exp(-t/0.004))*exp(-t/0.055)':sample_rate=$SR:duration=0.12
    ,volume=1.0
    ,adelay=delays=200:all=1[c];
  [a][b][c]amix=inputs=3:normalize=0
    ,afade=type=in:start_time=0:duration=0.003:curve=tri
    ,afade=type=out:start_time=0.312:duration=0.008:curve=tri[out]"
finish rest-done -3

# ---------------------------------------------------------------------------
# 6. impact.wav — soft low-frequency body hit for a hard cut, ~300 ms. A THUD.
#
#    [a] the sub. A sine whose frequency falls exponentially from 115 Hz to
#        55 Hz with a 35 ms time constant — the classic drop that makes a hit
#        read as weight rather than as a tone. The phase is integrated
#        analytically so the sweep is continuous and click-free:
#            f(t)   = 55 + 60*exp(-t/0.035)
#            phase  = 2*PI*(55*t + 60*0.035*(1 - exp(-t/0.035)))
#        A 22% second harmonic keeps it audible on laptop and phone speakers
#        that cannot reproduce 55 Hz. Amplitude decays with an 85 ms constant.
#    [b] the transient. 14 ms of white noise — fourteen milliseconds, not a
#        sweep — lowpassed twice at 700 Hz and highpassed at 60 Hz, so it is a
#        dull knock on the front of the sub, not air. It is fully decayed
#        before t = 15 ms; there is no sustained noise anywhere in this file.
#    A 22 Hz highpass on the mix removes the DC the fast envelope leaves behind.
# ---------------------------------------------------------------------------
synth impact "
  aevalsrc=exprs='(sin(2*PI*(55*t+60*0.035*(1-exp(-t/0.035))))+0.22*sin(4*PI*(55*t+60*0.035*(1-exp(-t/0.035)))))*exp(-t/0.085)':sample_rate=$SR:duration=0.30
    ,volume=1.0[a];
  anoisesrc=color=white:amplitude=0.9:duration=0.014:sample_rate=$SR:seed=303
    ,highpass=frequency=60:poles=2
    ,lowpass=frequency=700:poles=2
    ,lowpass=frequency=700:poles=2
    ,afade=type=out:start_time=0.001:duration=0.013:curve=exp
    ,volume=0.30[b];
  [a][b]amix=inputs=2:normalize=0
    ,highpass=frequency=22:poles=2
    ,afade=type=in:start_time=0:duration=0.002:curve=tri
    ,afade=type=out:start_time=0.288:duration=0.012:curve=tri[out]"
finish impact -3

# ---------------------------------------------------------------------------
# 7. count.wav — tiny high tick for a rapidly counting number, ~20 ms.
#
#    This one gets fired dozens of times per second, so the design goal is
#    "perceptible but never fatiguing": white noise bandpassed at 3.2 kHz and
#    then lowpassed at 6.5 kHz to strip the fizz that makes repeated ticks
#    abrasive, a 2100 Hz pip with a 3.5 ms decay for a hint of pitch, a 2 ms
#    triangular fade-in so nothing lands as an instantaneous edge, and a level
#    ~6 dB under tap.
# ---------------------------------------------------------------------------
synth count "
  anoisesrc=color=white:amplitude=0.9:duration=0.02:sample_rate=$SR:seed=404
    ,bandpass=frequency=3200:width_type=h:width=2200
    ,lowpass=frequency=6500:poles=2
    ,afade=type=out:start_time=0.0015:duration=0.0175:curve=exp
    ,volume=1.0[a];
  aevalsrc=exprs='sin(2*PI*2100*t)*(1-exp(-t/0.0006))*exp(-t/0.0035)':sample_rate=$SR:duration=0.02
    ,volume=0.38[b];
  [a][b]amix=inputs=2:normalize=0
    ,afade=type=in:start_time=0:duration=0.002:curve=tri
    ,afade=type=out:start_time=0.016:duration=0.004:curve=tri[out]"
finish count -3

# ---------------------------------------------------------------------------
# 10. pop.wav — a card landing on screen, ~90 ms. A round low-mid "pock".
#
#     Same family as tap but a different object: tap is a fingertip on glass
#     (bright, dry, noise-led, 60 ms), pop is a small solid thing settling
#     (round, pitched, body-led, 90 ms). The difference is carried by making
#     the TONE dominant here rather than the noise, and putting it an octave
#     below tap's 560 Hz pip.
#     A sine drops from 320 Hz to 175 Hz with a 20 ms time constant — the same
#     analytic phase integration as impact.wav, just smaller and faster — with
#     15% second harmonic for body on phone speakers. 2 ms attack, 28 ms decay.
#     The front transient is only 8 ms of noise, lowpassed TWICE at 900 Hz and
#     highpassed at 120 Hz: enough to mark the contact, far too dark to click.
# ---------------------------------------------------------------------------
synth pop "
  aevalsrc=exprs='(sin(2*PI*(175*t+2.90*(1-exp(-t/0.020))))+0.15*sin(4*PI*(175*t+2.90*(1-exp(-t/0.020)))))*(1-exp(-t/0.002))*exp(-t/0.028)':sample_rate=$SR:duration=0.09
    ,volume=1.0[a];
  anoisesrc=color=white:amplitude=0.9:duration=0.008:sample_rate=$SR:seed=606
    ,highpass=frequency=120:poles=2
    ,lowpass=frequency=900:poles=2
    ,lowpass=frequency=900:poles=2
    ,afade=type=out:start_time=0.0008:duration=0.0072:curve=exp
    ,volume=0.18[b];
  [a][b]amix=inputs=2:normalize=0
    ,highpass=frequency=35:poles=2
    ,afade=type=in:start_time=0:duration=0.002:curve=tri
    ,afade=type=out:start_time=0.082:duration=0.008:curve=tri[out]"
finish pop -3

# ===========================================================================
# ElevenLabs-sourced cues. See public/sfx/src/PROMPTS.md for the prompts and
# for the catalogue of prompts that failed. Trim windows below were found by
# measuring each take's 5-20 ms peak envelope, not by guessing.
# ===========================================================================

# ---------------------------------------------------------------------------
# 8. tick.wav — smartwatch stepper detent, ~55 ms. Fires 5x as 150 -> 155 lb.
#
#    Source take is a mechanical keyboard switch: two presses, at t=0 and
#    t~95 ms. The second is the cleaner one — it rises -31 -> -17 -> -7 dBFS
#    across 90-100 ms and is fully decayed by 150 ms — so the window is
#    92-147 ms. Chosen over the "watch bezel" and "camera dial" takes because
#    those measured 95-99% of their energy above 4 kHz (thin, hissy, no body).
#    Isolating just the click still left this take at 82% above 4 kHz, so a
#    -6 dB shelf at 5 kHz rebalances it to 53% >4 kHz / 30% in 1-4 kHz / 15%
#    in 200-1000 Hz: still high-frequency-led, because that is what a small
#    metal detent actually is, but now with the body that stops it reading as
#    a hiss. A steeper -10 dB shelf was tried and moved it to 43% in 1-4 kHz,
#    which buys body at the cost of the crispness the brief asked for.
# ---------------------------------------------------------------------------
fromsrc tick tick.mp3 0.092 0.055 0.002 0.008 \
  "treble=gain=-6:frequency=5000:width_type=q:width=0.7"

# ---------------------------------------------------------------------------
# 9. swoosh.wav — a card flying across the screen into the bell, ~280 ms.
#
#    Deliberately a physical object, not air: a flicked wooden domino card.
#    The take has three contacts — a flick at 390 ms, the main landing at
#    490 ms (the loudest point in the file) and a settle at ~550 ms. The
#    window keeps all three, which is the actual story: it is thrown, it
#    lands, it settles. Only 1.4% of its energy sits above 4 kHz, which is
#    the measurement that says this is not the generic noise-sweep whoosh.
# ---------------------------------------------------------------------------
fromsrc swoosh swoosh.mp3 0.375 0.280 0.003 0.030

# ---------------------------------------------------------------------------
# 10. ding.wav — the bell the card lands in, ~600 ms.
#
#     A struck music-box bell, ~1480 Hz fundamental. Picked over four other
#     takes on two measurements: 94.9% of its energy is in the 1-4 kHz band
#     where a bell's fundamental belongs, and only 0.1% is above 4 kHz — the
#     rejected takes ran 24-90% above 4 kHz and would have read as shrill.
#     Its natural decay runs well past a second, but the source is quiet
#     (-21 dBFS) so normalising to -3 lifts its noise floor to about -38 dBFS.
#     Trimming at 600 ms with a long 120 ms fade lands on the ring while it is
#     still 20+ dB above that floor, so no hiss tail is exposed.
# ---------------------------------------------------------------------------
fromsrc ding ding.mp3 0.000 0.600 0.003 0.120

# ---------------------------------------------------------------------------
# 11. screen.wav — the phone changing to a different screen, ~250 ms.
#
#     Fires constantly, so the brief was "unobtrusive and never fatiguing".
#     A muted card set down on a smooth surface: the take is silent until a
#     single soft contact at 295 ms, so the window starts 5 ms ahead of it.
#     85.6% of the energy sits in 200-1000 Hz with 0.1% above 4 kHz — soft and
#     neutral, with none of the high-frequency edge that makes a repeated cue
#     wear on you. The rejected alternative measured 100% below 200 Hz: a
#     formless sub with no attack at all.
# ---------------------------------------------------------------------------
fromsrc screen screen.mp3 0.290 0.250 0.002 0.040

# ---------------------------------------------------------------------------
# 12. fill.wav — a progress bar or goal meter filling, ~720 ms.
#
#     An ASCENDING glass-xylophone run, measured climbing 1260 -> 2095 Hz,
#     that lands on a final struck note at ~660 ms and rings out. Discrete
#     steps were chosen over a smooth glissando on purpose: a continuous
#     upward pitch sweep IS the riser cliché the brief ruled out, whereas
#     separate ascending notes read as increments — which is literally what a
#     filling meter is doing. Two "rising synthesizer" takes were rejected
#     after measurement showed their pitch actually FELL (560 -> 275 Hz).
# ---------------------------------------------------------------------------
fromsrc fill fill.mp3 0.030 0.720 0.005 0.100

# ---------------------------------------------------------------------------
# 13. reveal.wav — one UI element appearing and settling, ~500 ms.
#
#     A single soft mallet note on a wooden marimba bar. Peak is at t=0 and
#     the decay is cleanly monotonic from -24 dBFS all the way down, so it is
#     unambiguously one event with no tail — exactly the brief. 98.6% of its
#     energy is in 200-1000 Hz, which is what makes it read warm rather than
#     bright, and keeps it distinct from the higher, harder tap.
# ---------------------------------------------------------------------------
fromsrc reveal reveal.mp3 0.000 0.500 0.003 0.080

# ---------------------------------------------------------------------------
# 14. sweep.wav — the accent edge that transforms the app, ~900 ms.
#
#     REPLACED. The first version of this cue was a "crystalline shimmer
#     across glass" take with 24.1% of its energy above 4 kHz and its peak
#     held for 320 ms. The director's verdict was that it sounded like an
#     electric cutter cutting metal, and acoustically that is exactly what
#     those two numbers describe: bright inharmonic content that sustains
#     does not read as an event happening, it reads as a tool running.
#
#     This take is a thick soft pillow pressed slowly and released — chosen
#     because it was the only candidate of ten that had a real ARC (it builds
#     to a peak at ~320 ms and falls away) rather than a flat wash. Flat
#     textures were rejected on principle: a cloth-wipe take measured lovely
#     and warm but held its peak for 480 ms, which is the same "tool running"
#     failure in a friendlier material.
#
#     The only processing is a highpass. The raw take is 98% below 200 Hz —
#     so low it is nearly inaudible on a laptop or phone, most of its energy
#     living under the speaker's rolloff. A 4-pole highpass at 220 Hz moves
#     it to 56% below 200 Hz / 44% in 200-1000 Hz: still low-weighted and
#     warm, but now with real presence in the band every device can actually
#     reproduce. Nothing is boosted; sub-bass nobody can hear is removed so
#     the -3 dBFS normalisation is spent on the audible part instead.
#
#     Measured, delivered: 0.0% above 4 kHz (limit 5%), 100% below 1 kHz
#     (floor 55%), peak held 40 ms (limit 120 ms). There is no energy at all
#     above 1 kHz, so this cue cannot read as metallic under any playback.
# ---------------------------------------------------------------------------
fromsrc sweep sweep.mp3 0.000 0.900 0.010 0.100 \
  "highpass=frequency=220:poles=2,highpass=frequency=220:poles=2"

echo "make-sfx: done — $(ls -1 "$OUT_DIR"/*.wav | wc -l) files in $OUT_DIR"
